spring.application.name=airBnbApp

# DB Configurations
spring.datasource.url=jdbc:postgresql://localhost:5432/airBnb
spring.datasource.username=postgres
spring.datasource.password=Shikhil@4
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.servlet.context-path=/api/v1

# Security Configs
jwt.secretKey=n5hj64bh5jn3ij6n54j43nj6njh56j43n6j5j4ntj34nhb5hj43no